baseurl = ""
languageCode = "en-us"
theme = "hugo-kiera"
paginate = 5

[params]
  contentTypeName = "post"
  themeColor = "green"

[languages]
  [languages.en]
    title = "Simple Jenkins Test Site"
    subtitle = "A simple site to test out Jenkinsfile"
    keywords = ""
    copyright = ""
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Jenkins SSG"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"

  [[languages.en.menu.main]]
    identifier = "theme-docs"
    name = "Theme Homepage"
    url = "https://github.com/panr/hugo-theme-terminal/"
